// user
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

// Advocates
export const GET_ADVOCATE_LIST = 'GET_ADVOCATE_LIST';
export const GET_ADVOCATE_LIST_SUCCESS = 'GET_ADVOCATE_LIST_SUCCESS';

export const CREATE_ADVOCATE = 'CREATE_ADVOCATE';
export const CREATE_ADVOCATE_SUCCESS = 'CREATE_ADVOCATE_SUCCESS';

export const UPDATE_ADVOCATE = 'UPDATE_ADVOCATE';
export const UPDATE_ADVOCATE_SUCCESS = 'UPDATE_ADVOCATE_SUCCESS';

export const DELETE_ADVOCATE_LIST = 'DELETE_ADVOCATE_LIST';
export const DELETE_ADVOCATE_LIST_SUCCESS = 'DELETE_ADVOCATE_LIST_SUCCESS';

// Manage
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';

export const SEND_HELP_DESK = 'SEND_HELP_DESK';
